// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  /**
   # @ngdoc function
   # @name frontApp.controller:AccountListCtrl
   # @description
   # # AccountListCtrl
   # Controller of the frontApp
  */

  angular.module('frontApp').controller('AccountListCtrl', [
    "$scope", "Api", "Const", function($scope, Api, Const) {
      $scope.full_items = JSON.parse(localStorage.getItem('dummy_response'));
      $scope.current_size = Math.min(Const.AccountList.page_size, $scope.full_items.length);
      $scope.items = $scope.full_items.slice(0, $scope.current_size);
      return $scope.loadMore = function() {
        var new_item, new_items, next_size, _i, _len;
        next_size = Math.min($scope.current_size + Const.AccountList.page_size, $scope.full_items.length);
        new_items = $scope.full_items.slice($scope.current_size, next_size);
        for (_i = 0, _len = new_items.length; _i < _len; _i++) {
          new_item = new_items[_i];
          $scope.items.push(new_item);
        }
        return $scope.current_size = next_size;
      };
    }
  ]);

}).call(this);
