// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  /**
   # @ngdoc function
   # @name frontApp.controller:MainCtrl
   # @description
   # # MainCtrl
   # Controller of the frontApp
  */

  angular.module('frontApp').controller('MainCtrl', function($scope) {});

}).call(this);
