// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('frontApp').factory('Api', function($http) {
    var host;
    host = 'http://127.0.0.1:3000';
    return {
      getIllustrators: function(screen_name) {
        return $http.get("" + host + "/twitter_accounts/" + screen_name + "/illustrators.json");
      }
    };
  });

}).call(this);
