// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('frontApp').factory('Const', function() {
    return {
      AccountList: {
        page_size: 100
      }
    };
  });

}).call(this);
