// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('frontApp').factory('Const', function() {
    return {
      AccountList: {
        page_size: 100,
        modal_width: 640,
        modal_height: 480
      }
    };
  });

}).call(this);
